### ISSUE TITLE
Potential bug with supporting connections between non-devices

### ISSUE THREAD

**Issue by blinklet** [nre-learning/syringe#113]
I tried to abuse antidote-selfmedicate and define a lab of three linux nodes connected together in a ring topology so I could test open-source routing software like FRR. 

It did not work because:
1) I re-used the utility container as a devices endpoint. But Antidote wants to configure devices using NAPALM. I tried to fake it out using blank configuration files but that just caused an error.
2) I created three utilities endpoints and tried to make connections between them. This also failed because Antidote will not add new interfaces to, and create connections between, utilities endpoints (even though the lesson validated OK).

I don't even know if the antidotelabs/utility image is suitable but I wanted to try it. I suspect I'll see the same issue if I try to create a custom image with Linux/FRR.

**Request:**
I suggest you allow Antidote to create connections between utilities endpoints, or set Antidote to not try to run NAPALM on devices endpoints if the configuration files are blank.

Longer term, I suggest you enable Ansible in addition to NAPALM so Antidote can also configure labs that run open-source systems like Linux/FRR.

**Comment by blinklet** [comment]
The lesson definition file I used was:

```
---
lessonName: Lab connections
lessonId: 101
category: fundamentals
tier: local
description: Connect three Utility containers together.
slug: Networking

utilities:
- name: server1
  image: antidotelabs/utility
- name: server2
  image: antidotelabs/utility
- name: server3
  image: antidotelabs/utility


connections:
- a: server1
  b: server2
- a: server2
  b: server3
- a: server3
  b: server1

stages:
  - id: 1
    description: Configure IP interfaces on each node
```

I can't capture shell output, because i see a new issue where the shell does not launch.

When I ran the `ip link show` command on each utility shell, I saw the endpoint like eth0@if24, but no additional interfaces that I was expecting.
